namespace AcDream.App.Tests.UI;

/// <summary>
/// The binding source behind the sample plugin panel fixture in
/// <c>UI/fixtures/plugin-panel</c>. It plays the part a plugin's own panel
/// class plays at runtime: every <c>{Name}</c> the fixture markup references
/// resolves to a public member here, with the shape the markup engine
/// requires for that attribute — a bool for a visibility or checkbox, an
/// <see cref="Action"/> for a click, an <see cref="Action{T}"/> of int for a
/// row click, a list for a column's rows, and so on.
///
/// The members are deliberately anonymous. The fixture exists to exercise the
/// markup engine over a realistic, large panel set — nine tabs, wide
/// multi-column tables, anchored resize, popups — not to describe any
/// particular plugin's features, so the names carry no domain meaning and
/// nothing here has to change when a real plugin changes.
/// </summary>
internal sealed class SamplePluginPanelBindings
{
    /// <summary>The icon id every row of the fixture's first icon column
    /// reports. The sample icon resolver hands an id straight back as the
    /// texture, so a draw carrying this id came from that column.</summary>
    internal const uint FirstRowIconId = 0x06009001u;

    /// <summary>The same for the column immediately to its right.</summary>
    internal const uint SecondRowIconId = 0x06009002u;

    public bool Flag1 { get; set; } = true;
    public bool Flag2 { get; set; } = true;
    public Action Command1 { get; set; } = () => { };
    public bool Flag3 { get; set; } = true;
    public bool Flag4 { get; set; } = true;
    public Action Command2 { get; set; } = () => { };
    public bool Flag5 { get; set; } = true;
    public bool Flag6 { get; set; } = true;
    public Action Command3 { get; set; } = () => { };
    public bool Flag7 { get; set; } = true;
    public bool Flag8 { get; set; } = true;
    public Action Command4 { get; set; } = () => { };
    public bool Flag9 { get; set; } = true;
    public bool Flag10 { get; set; } = true;
    public Action Command5 { get; set; } = () => { };
    public bool Flag11 { get; set; } = true;
    public bool Flag12 { get; set; } = true;
    public Action Command6 { get; set; } = () => { };
    public bool Flag13 { get; set; } = true;
    public bool Flag14 { get; set; } = true;
    public Action Command7 { get; set; } = () => { };
    public bool Flag15 { get; set; } = true;
    public bool Flag16 { get; set; } = true;
    public Action Command8 { get; set; } = () => { };
    public bool Flag17 { get; set; } = true;
    public bool Flag18 { get; set; } = true;
    public Action Command9 { get; set; } = () => { };
    public bool Flag19 { get; set; } = true;
    public bool Flag20 { get; set; } = true;
    public string Caption1 { get; set; } = "Caption1";
    public Action<string> TextCommand1 { get; set; } = _ => { };
    public string Caption2 { get; set; } = "Caption2";
    public Action<string> TextCommand2 { get; set; } = _ => { };
    public string Caption3 { get; set; } = "Caption3";
    public Action<string> TextCommand3 { get; set; } = _ => { };
    public string Caption4 { get; set; } = "Caption4";
    public Action<string> TextCommand4 { get; set; } = _ => { };
    public Action Command10 { get; set; } = () => { };
    public Action Command11 { get; set; } = () => { };
    public Action Command12 { get; set; } = () => { };
    public bool Flag21 { get; set; } = true;
    public Action Command13 { get; set; } = () => { };
    public bool Flag22 { get; set; } = true;
    public Action Command14 { get; set; } = () => { };
    public bool Flag23 { get; set; } = true;
    public Action Command15 { get; set; } = () => { };
    public bool Flag24 { get; set; } = true;
    public Action Command16 { get; set; } = () => { };
    public bool Flag25 { get; set; } = true;
    public Action Command17 { get; set; } = () => { };
    public bool Flag26 { get; set; } = true;
    public Action Command18 { get; set; } = () => { };
    public bool Flag27 { get; set; } = true;
    public Action Command19 { get; set; } = () => { };
    public bool Flag28 { get; set; } = true;
    public Action Command20 { get; set; } = () => { };
    public bool Flag29 { get; set; } = true;
    public Action Command21 { get; set; } = () => { };
    public bool Flag30 { get; set; } = true;
    public Action Command22 { get; set; } = () => { };
    public bool Flag31 { get; set; } = true;
    public Action Command23 { get; set; } = () => { };
    public bool Flag32 { get; set; } = true;
    public Action Command24 { get; set; } = () => { };
    public bool Flag33 { get; set; } = true;
    public Action Command25 { get; set; } = () => { };
    public bool Flag34 { get; set; } = true;
    public Action Command26 { get; set; } = () => { };
    public bool Flag35 { get; set; } = true;
    public Action Command27 { get; set; } = () => { };
    public bool Flag36 { get; set; } = true;
    public Action Command28 { get; set; } = () => { };
    public bool Flag37 { get; set; } = true;
    public Action Command29 { get; set; } = () => { };
    public bool Flag38 { get; set; } = true;
    public Action Command30 { get; set; } = () => { };
    public bool Flag39 { get; set; } = true;
    public Action Command31 { get; set; } = () => { };
    public bool Flag40 { get; set; } = true;
    public Action Command32 { get; set; } = () => { };
    public bool Flag41 { get; set; } = true;
    public Action Command33 { get; set; } = () => { };
    public bool Flag42 { get; set; } = true;
    public string Caption5 { get; set; } = "Caption5";
    public Action<string> TextCommand5 { get; set; } = _ => { };
    public string Caption6 { get; set; } = "Caption6";
    public Action<string> TextCommand6 { get; set; } = _ => { };
    public Action Command34 { get; set; } = () => { };
    public bool Flag43 { get; set; } = true;
    public Action Command35 { get; set; } = () => { };
    public bool Flag44 { get; set; } = true;
    public string Caption7 { get; set; } = "Caption7";
    public bool Flag45 { get; set; } = true;
    public Action<string> TextCommand7 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows1 { get; set; } = ["TextRows1 a", "TextRows1 b", "TextRows1 c"];
    public string Caption8 { get; set; } = "Caption8";
    public Action Command36 { get; set; } = () => { };
    public Action Command37 { get; set; } = () => { };
    public Action Command38 { get; set; } = () => { };
    public bool Flag46 { get; set; } = true;
    public Action<string> TextCommand8 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows2 { get; set; } = ["TextRows2 a", "TextRows2 b", "TextRows2 c"];
    public string Caption9 { get; set; } = "Caption9";
    public Action Command39 { get; set; } = () => { };
    public Action Command40 { get; set; } = () => { };
    public Action<string> TextCommand9 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows3 { get; set; } = ["TextRows3 a", "TextRows3 b", "TextRows3 c"];
    public string Caption10 { get; set; } = "Caption10";
    public Action Command41 { get; set; } = () => { };
    public Action<string> TextCommand10 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows4 { get; set; } = ["TextRows4 a", "TextRows4 b", "TextRows4 c"];
    public string Caption11 { get; set; } = "Caption11";
    public Action Command42 { get; set; } = () => { };
    public string Caption12 { get; set; } = "Caption12";
    public bool Flag47 { get; set; } = true;
    public Action<float> ScalarCommand1 { get; set; } = _ => { };
    public float Scalar1 { get; set; } = 0.5f;
    public string Caption13 { get; set; } = "Caption13";
    public Action<float> ScalarCommand2 { get; set; } = _ => { };
    public float Scalar2 { get; set; } = 0.5f;
    public string Caption14 { get; set; } = "Caption14";
    public Action<float> ScalarCommand3 { get; set; } = _ => { };
    public float Scalar3 { get; set; } = 0.5f;
    public string Caption15 { get; set; } = "Caption15";
    public Action<float> ScalarCommand4 { get; set; } = _ => { };
    public float Scalar4 { get; set; } = 0.5f;
    public string Caption16 { get; set; } = "Caption16";
    public Action<float> ScalarCommand5 { get; set; } = _ => { };
    public float Scalar5 { get; set; } = 0.5f;
    public string Caption17 { get; set; } = "Caption17";
    public Action<float> ScalarCommand6 { get; set; } = _ => { };
    public float Scalar6 { get; set; } = 0.5f;
    public string Caption18 { get; set; } = "Caption18";
    public Action<float> ScalarCommand7 { get; set; } = _ => { };
    public float Scalar7 { get; set; } = 0.5f;
    public string Caption19 { get; set; } = "Caption19";
    public Action<float> ScalarCommand8 { get; set; } = _ => { };
    public float Scalar8 { get; set; } = 0.5f;
    public string Caption20 { get; set; } = "Caption20";
    public Action<float> ScalarCommand9 { get; set; } = _ => { };
    public float Scalar9 { get; set; } = 0.5f;
    public string Caption21 { get; set; } = "Caption21";
    public Action Command43 { get; set; } = () => { };
    public bool Flag48 { get; set; } = true;
    public Action Command44 { get; set; } = () => { };
    public bool Flag49 { get; set; } = true;
    public string Caption22 { get; set; } = "Caption22";
    public string Caption23 { get; set; } = "Caption23";
    public bool Flag50 { get; set; } = true;
    public int SelectedRow1 { get; set; } = 0;
    public Action<int> RowCommand1 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows1 { get; set; } = [true, false, true];
    public Action<int> RowCommand2 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows2 { get; set; } = [true, false, true];
    public Action<int> RowCommand3 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows3 { get; set; } = [true, false, true];
    public Action<int> RowCommand4 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows4 { get; set; } = [true, false, true];
    public Action<int> RowCommand5 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows5 { get; set; } = [true, false, true];
    public Action<int> RowCommand6 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows6 { get; set; } = [true, false, true];
    public Action<int> RowCommand7 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows7 { get; set; } = [true, false, true];
    public Action<int> RowCommand8 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows8 { get; set; } = [true, false, true];
    public Action<int> RowCommand9 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows9 { get; set; } = [true, false, true];
    public Action<int> RowCommand10 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows10 { get; set; } = [true, false, true];
    public Action<int> RowCommand11 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows11 { get; set; } = [true, false, true];
    public Action<int> RowCommand12 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows12 { get; set; } = [true, false, true];
    public Action<int> RowCommand13 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows13 { get; set; } = [true, false, true];
    public Action<int> RowCommand14 { get; set; } = _ => { };
    public IReadOnlyList<bool> CheckRows14 { get; set; } = [true, false, true];
    public Action<int> RowCommand15 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows5 { get; set; } = ["TextRows5 a", "TextRows5 b", "TextRows5 c"];
    public Action<int> RowCommand16 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows6 { get; set; } = ["TextRows6 a", "TextRows6 b", "TextRows6 c"];
    public Action<int> RowCommand17 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows7 { get; set; } = ["TextRows7 a", "TextRows7 b", "TextRows7 c"];
    public Action<int> RowCommand18 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows8 { get; set; } = ["TextRows8 a", "TextRows8 b", "TextRows8 c"];
    public Action<int> RowCommand19 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows9 { get; set; } = ["TextRows9 a", "TextRows9 b", "TextRows9 c"];
    public Action<int> RowCommand20 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows10 { get; set; } = ["TextRows10 a", "TextRows10 b", "TextRows10 c"];
    public Action<int> RowCommand21 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows11 { get; set; } = ["TextRows11 a", "TextRows11 b", "TextRows11 c"];
    public Action<int> RowCommand22 { get; set; } = _ => { };
    public IReadOnlyList<uint> IconRows1 { get; set; } = [0x6009001u, 0x6009001u, 0x6009001u];
    public Action<int> RowCommand23 { get; set; } = _ => { };
    public IReadOnlyList<uint> IconRows2 { get; set; } = [0x6009002u, 0x6009002u, 0x6009002u];
    public Action<int> RowCommand24 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows12 { get; set; } = ["TextRows12 a", "TextRows12 b", "TextRows12 c"];
    public Action<int> RowCommand25 { get; set; } = _ => { };
    public string Caption24 { get; set; } = "Caption24";
    public Action<string> TextCommand11 { get; set; } = _ => { };
    public Action Command45 { get; set; } = () => { };
    public Action Command46 { get; set; } = () => { };
    public bool Flag51 { get; set; } = true;
    public int SelectedRow2 { get; set; } = 0;
    public Action<int> RowCommand26 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows13 { get; set; } = ["TextRows13 a", "TextRows13 b", "TextRows13 c"];
    public Action<int> RowCommand27 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows14 { get; set; } = ["TextRows14 a", "TextRows14 b", "TextRows14 c"];
    public Action<int> RowCommand28 { get; set; } = _ => { };
    public Action Command47 { get; set; } = () => { };
    public Action Command48 { get; set; } = () => { };
    public Action Command49 { get; set; } = () => { };
    public bool Flag52 { get; set; } = true;
    public int SelectedRow3 { get; set; } = 0;
    public Action<int> RowCommand29 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows15 { get; set; } = ["TextRows15 a", "TextRows15 b", "TextRows15 c"];
    public int SelectedRow4 { get; set; } = 0;
    public Action<int> RowCommand30 { get; set; } = _ => { };
    public IReadOnlyList<uint> IconRows3 { get; set; } = [0x6009003u, 0x6009003u, 0x6009003u];
    public Action<int> RowCommand31 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows16 { get; set; } = ["TextRows16 a", "TextRows16 b", "TextRows16 c"];
    public Action Command50 { get; set; } = () => { };
    public Action Command51 { get; set; } = () => { };
    public Action Command52 { get; set; } = () => { };
    public Action Command53 { get; set; } = () => { };
    public string Caption25 { get; set; } = "Caption25";
    public bool Flag53 { get; set; } = true;
    public int SelectedRow5 { get; set; } = 0;
    public Action<int> RowCommand32 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows17 { get; set; } = ["TextRows17 a", "TextRows17 b", "TextRows17 c"];
    public Action Command54 { get; set; } = () => { };
    public int SelectedRow6 { get; set; } = 0;
    public Action<int> RowCommand33 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows18 { get; set; } = ["TextRows18 a", "TextRows18 b", "TextRows18 c"];
    public Action Command55 { get; set; } = () => { };
    public bool Flag54 { get; set; } = true;
    public int SelectedRow7 { get; set; } = 0;
    public Action<int> RowCommand34 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows19 { get; set; } = ["TextRows19 a", "TextRows19 b", "TextRows19 c"];
    public Action<int> RowCommand35 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows20 { get; set; } = ["TextRows20 a", "TextRows20 b", "TextRows20 c"];
    public IReadOnlyList<string> TextRows21 { get; set; } = ["TextRows21 a", "TextRows21 b", "TextRows21 c"];
    public Action<int> RowCommand36 { get; set; } = _ => { };
    public Action<string> TextCommand12 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows22 { get; set; } = ["TextRows22 a", "TextRows22 b", "TextRows22 c"];
    public string Caption26 { get; set; } = "Caption26";
    public Action<string> TextCommand13 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows23 { get; set; } = ["TextRows23 a", "TextRows23 b", "TextRows23 c"];
    public string Caption27 { get; set; } = "Caption27";
    public Action Command56 { get; set; } = () => { };
    public Action Command57 { get; set; } = () => { };
    public Action Command58 { get; set; } = () => { };
    public Action Command59 { get; set; } = () => { };
    public Action Command60 { get; set; } = () => { };
    public Action Command61 { get; set; } = () => { };
    public Action Command62 { get; set; } = () => { };
    public Action Command63 { get; set; } = () => { };
    public Action<string> TextCommand14 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows24 { get; set; } = ["TextRows24 a", "TextRows24 b", "TextRows24 c"];
    public string Caption28 { get; set; } = "Caption28";
    public Action Command64 { get; set; } = () => { };
    public string Caption29 { get; set; } = "Caption29";
    public Action<string> TextCommand15 { get; set; } = _ => { };
    public Action Command65 { get; set; } = () => { };
    public string Caption30 { get; set; } = "Caption30";
    public Action<string> TextCommand16 { get; set; } = _ => { };
    public Action<string> TextCommand17 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows25 { get; set; } = ["TextRows25 a", "TextRows25 b", "TextRows25 c"];
    public string Caption31 { get; set; } = "Caption31";
    public string Caption32 { get; set; } = "Caption32";
    public string Caption33 { get; set; } = "Caption33";
    public bool Flag55 { get; set; } = true;
    public int SelectedRow8 { get; set; } = 0;
    public Action<int> RowCommand37 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows26 { get; set; } = ["TextRows26 a", "TextRows26 b", "TextRows26 c"];
    public Action<int> RowCommand38 { get; set; } = _ => { };
    public IReadOnlyList<uint> IconRows4 { get; set; } = [0x6009004u, 0x6009004u, 0x6009004u];
    public Action<int> RowCommand39 { get; set; } = _ => { };
    public IReadOnlyList<uint> IconRows5 { get; set; } = [0x6009005u, 0x6009005u, 0x6009005u];
    public Action<int> RowCommand40 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows27 { get; set; } = ["TextRows27 a", "TextRows27 b", "TextRows27 c"];
    public IReadOnlyList<string> TextRows28 { get; set; } = ["TextRows28 a", "TextRows28 b", "TextRows28 c"];
    public IReadOnlyList<string> TextRows29 { get; set; } = ["TextRows29 a", "TextRows29 b", "TextRows29 c"];
    public Action<string> TextCommand18 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows30 { get; set; } = ["TextRows30 a", "TextRows30 b", "TextRows30 c"];
    public string Caption34 { get; set; } = "Caption34";
    public Action Command66 { get; set; } = () => { };
    public string Caption35 { get; set; } = "Caption35";
    public int SelectedRow9 { get; set; } = 0;
    public Action<int> RowCommand41 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows31 { get; set; } = ["TextRows31 a", "TextRows31 b", "TextRows31 c"];
    public IReadOnlyList<string> TextRows32 { get; set; } = ["TextRows32 a", "TextRows32 b", "TextRows32 c"];
    public Action<int> RowCommand42 { get; set; } = _ => { };
    public int SelectedRow10 { get; set; } = 0;
    public IReadOnlyList<bool> CheckRows15 { get; set; } = [true, false, true];
    public Action<int> RowCommand43 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows33 { get; set; } = ["TextRows33 a", "TextRows33 b", "TextRows33 c"];
    public string Caption36 { get; set; } = "Caption36";
    public Action<string> TextCommand19 { get; set; } = _ => { };
    public Action<string> TextCommand20 { get; set; } = _ => { };
    public string Caption37 { get; set; } = "Caption37";
    public bool Flag56 { get; set; } = true;
    public int SelectedRow11 { get; set; } = 0;
    public Action<int> RowCommand44 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows34 { get; set; } = ["TextRows34 a", "TextRows34 b", "TextRows34 c"];
    public string Caption38 { get; set; } = "Caption38";
    public Action<string> TextCommand21 { get; set; } = _ => { };
    public Action Command67 { get; set; } = () => { };
    public bool Flag57 { get; set; } = true;
    public string Caption39 { get; set; } = "Caption39";
    public Action<string> TextCommand22 { get; set; } = _ => { };
    public Action<string> TextCommand23 { get; set; } = _ => { };
    public Action Command68 { get; set; } = () => { };
    public Action Command69 { get; set; } = () => { };
    public Action Command70 { get; set; } = () => { };
    public int SelectedRow12 { get; set; } = 0;
    public Action<int> RowCommand45 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows35 { get; set; } = ["TextRows35 a", "TextRows35 b", "TextRows35 c"];
    public Action<string> TextCommand24 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows36 { get; set; } = ["TextRows36 a", "TextRows36 b", "TextRows36 c"];
    public string Caption40 { get; set; } = "Caption40";
    public string Caption41 { get; set; } = "Caption41";
    public Action Command71 { get; set; } = () => { };
    public Action Command72 { get; set; } = () => { };
    public string Caption42 { get; set; } = "Caption42";
    public Action Command73 { get; set; } = () => { };
    public Action Command74 { get; set; } = () => { };
    public string Caption43 { get; set; } = "Caption43";
    public Action<string> TextCommand25 { get; set; } = _ => { };
    public Action<string> TextCommand26 { get; set; } = _ => { };
    public Action Command75 { get; set; } = () => { };
    public Action Command76 { get; set; } = () => { };
    public Action Command77 { get; set; } = () => { };
    public Action Command78 { get; set; } = () => { };
    public Action Command79 { get; set; } = () => { };
    public Action Command80 { get; set; } = () => { };
    public bool Flag58 { get; set; } = true;
    public Action Command81 { get; set; } = () => { };
    public bool Flag59 { get; set; } = true;
    public Action Command82 { get; set; } = () => { };
    public bool Flag60 { get; set; } = true;
    public string Caption44 { get; set; } = "Caption44";
    public Action Command83 { get; set; } = () => { };
    public Action Command84 { get; set; } = () => { };
    public bool Flag61 { get; set; } = true;
    public string Caption45 { get; set; } = "Caption45";
    public Action<string> TextCommand27 { get; set; } = _ => { };
    public Action<string> TextCommand28 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows37 { get; set; } = ["TextRows37 a", "TextRows37 b", "TextRows37 c"];
    public string Caption46 { get; set; } = "Caption46";
    public Action<string> TextCommand29 { get; set; } = _ => { };
    public IReadOnlyList<string> TextRows38 { get; set; } = ["TextRows38 a", "TextRows38 b", "TextRows38 c"];
    public string Caption47 { get; set; } = "Caption47";
    public string Caption48 { get; set; } = "Caption48";
    public Action<string> TextCommand30 { get; set; } = _ => { };
    public string Caption49 { get; set; } = "Caption49";
    public Action<string> TextCommand31 { get; set; } = _ => { };
    public string Caption50 { get; set; } = "Caption50";
    public Action<string> TextCommand32 { get; set; } = _ => { };
    public string Caption51 { get; set; } = "Caption51";
    public Action Command85 { get; set; } = () => { };
    public Action Command86 { get; set; } = () => { };
    public string Caption52 { get; set; } = "Caption52";
    public Action Command87 { get; set; } = () => { };
    public Action Command88 { get; set; } = () => { };
    public Action Command89 { get; set; } = () => { };
    public Action Command90 { get; set; } = () => { };
    public Action Command91 { get; set; } = () => { };
    public Action Command92 { get; set; } = () => { };
    public Action Command93 { get; set; } = () => { };
    public string Caption53 { get; set; } = "Caption53";
}
